existing:
    normal:
        files:
            - .bashrc: /home/jerin/.bashrc
            - .bash_profile: /home/jerin/.bash_profile
            - .xinitrc: /home/jerin/.xinitrc
            - .xprofile: /home/jerin/.xprofile
            - .Xresources : /home/jerin/.Xresources
            - .xscreensaver: /home/jerin/.xscreensaver
            - .vimrc: /home/jerin/.vimrc
            - .fonts.conf: /home/jerin/.fonts.conf
        folders:
            - .vim: /home/jerin/.vim
            - awesome: /home/jerin/.config/awesome

    protected:
        files:
            - asound.conf: /etc/asound.conf
            - lightdm-gtk-greeter.conf: /etc/lightdm/lightdm-gtk-greeter.conf
            - 50-synaptics.conf: /etc/X11/xorg.conf.d/50-synaptics.conf
        folders:
            - xinitrc.d: /etc/X11/xinit/xinitrc.d

